/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_test_test */

#ifndef _Included_test_test_test
#define _Included_test_test_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_test_test
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_test_test_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
